services:
  mysql:
    image: 'mysql:latest'
    container_name: mysql-container
    environment:
      - 'MYSQL_DATABASE=mslogindb'
      - 'MYSQL_PASSWORD=1234'
      - 'MYSQL_ROOT_PASSWORD=verysecret'
      - 'MYSQL_USER=user'
    ports:
      - '3306:3306'
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
    driver: local